#!/usr/bin/env python3

import subprocess
from math import trunc
import os
import time
from datetime import datetime
from sys import argv
from polybar_print import polybar_print

def to_num(input_str):
	output_str = ""
	for ch in input_str:
		if ch.isdigit():
			output_str += ch
	return (int(output_str))


#scroll_size = 45
scroll_position = 0
scroll_count = 0
scroll_velocity = 0

update_duration = 1

prev_time = time.time()

duration_cmd = "playerctl metadata --format '{{mpris:length}}'"
song_duration = str(subprocess.check_output(duration_cmd, shell=True))
song_duration = to_num(song_duration)

position_cmd = "playerctl metadata --format '{{position}}'"
position = str(subprocess.check_output(position_cmd, shell=True))
position = to_num(position)

current_pct = (position / song_duration) * 100

cmd = "playerctl metadata --format '{{title}} / {{artist}}" + \
"'"
output = str(subprocess.check_output(cmd, shell=True))[2:-3]

scroll_size = 16 if argv[1] == "0" else 80

if len(output) > scroll_size:
	output = output[:scroll_size] + "..."

output += " ┝"


if argv[1] == "0":
	for i in range(1, 26):
		if i*4 < current_pct:
			output += "━"
		else:
			output += "┄"
elif argv[1] == "1":
	for i in range(1, 51):
		if i*2 < current_pct:
			output += "━"
		else:
			output += "┄"

playing_check = str(subprocess.check_output(
    "playerctl status", shell=True))[2:-3]

if playing_check == "Playing":
	output = output + "┤"
else:
	print("")
	exit()

print(polybar_print(output))
